name: Deploy S3 Bucket

on:
  push:
    branches:
      - smurf-stf
      - master

    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Set up smurf                  
        uses: clouddrove/smurf@fix/stf-show
        with:
          version: v1.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verify AWS Identity (Debug Step 🔍)
        run: aws sts get-caller-identity

      - name: Smurf Terraform Init
        run: smurf stf init

      - name: Smurf Terraform Validate
        run: smurf stf validate

      - name: Smurf Terraform Show
        run: smurf stf show

      - name: Smurf Terraform Show json
        run: smurf stf show --json

      - name: Smurf Terraform Plan
        run: smurf stf plan --out=tfplan

      - name: Smurf Terraform Apply
        run: smurf stf apply tfplan